### ISSUE TITLE
Use lease file to determine the IP address for older version of libvirt and status file for newer one.

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/machine-driver-libvirt#15]
https://github.com/kubernetes/minikube/blob/master/pkg/drivers/kvm/network.go#L270-L276

**Comment by cfergeau** [comment]
Do we need to support such an old libvirt version (1.2.6 apparently)? I'm attempting to drop support for a libvirt version more recent than that in https://github.com/cfergeau/cluster-api-provider-libvirt/commit/4900df1a0733a5a114595ac741c3edcd78fcd396
I'd directly use the same API as `virsh domifaddr` (probably `virDomainInterfaceAddresses` ), but I suspect this is what the linked commit is doing when it says `TODO: for everything > 1002006, there is direct support in the libvirt-go for handling this`. Or maybe not now that I reread it.

**Comment by praveenkumar** [comment]
I think as part of our support matrix we also need to check if we can remove it all together.

**Comment by praveenkumar** [comment]
fixed #16
