### ISSUE TITLE
Create static binary for crc-driver-libvirt

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/machine-driver-libvirt#3]
We need to create the static binary for driver use case otherwise for a different version of libvirt user will see something following as error.

```
FATA crc-driver-libvirt does not have right version 
 Required: 0.11.0 
 Got: /usr/local/bin/crc-driver-libvirt: /lib64/libvirt.so.0: version `LIBVIRT_4.1.0' not found (required by /usr/local/bin/crc-driver-libvirt)
/usr/local/bin/crc-driver-libvirt: /lib64/libvirt.so.0: version `LIBVIRT_4.4.0' not found (required by /usr/local/bin/crc-driver-libvirt)
/usr/local/bin/crc-driver-libvirt: /lib64/libvirt.so.0: version `LIBVIRT_4.5.0' not found (required by /usr/local/bin/crc-driver-libvirt)
 use 'crc setup' command.
```

**Comment by cfergeau** [comment]
If you mean statically link the driver with libvirt.so, apparently some people in the skydive team have tried it, and this did not work out. So they've been using https://blog.digitalocean.com/introducing-go-qemu-and-go-libvirt/ instead.

**Comment by praveenkumar** [comment]
This is done using an older version of dep during the compile.
