### ISSUE TITLE
`crc-libvirt-driver version` shouldn't exit with return code 1 and also have output to stdout

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/machine-driver-libvirt#4]
Right now if I check `crc-libvirt-driver version` from the command line it always return a non-zero code and output is also in the stderr.

This is not an expected result and should be modified.

```
$ crc-driver-libvirt version
This is a hypervisor plugin binary for CodeReady Containers.
Please use this plugin through the main 'crc' binary.
(Driver version: 0.11.0, API version: 1)

$ echo $?
1
```

**Comment by gbraad** [comment]
this was related to standard behaviour... when no command is given it would still error out... Is this also (un)wanted?

**Comment by praveenkumar** [comment]
When no command given or any other argument are given then it should go with stderr like it is right now but in case of `version` command it will show the version and don't provide it in stderr.

https://github.com/code-ready/crc/blob/master/pkg/crc/preflight/preflight_checks_linux.go#L227-L233 right now we are checking the stderr output to get the version which shouldn't be expected for a cmd side.

**Comment by praveenkumar** [comment]
Already merged.
