### ISSUE TITLE
`GetState()` can return `state.Stopped` when libvirt VM still runs

### ISSUE THREAD

**Issue by cfergeau** [code-ready/machine-driver-libvirt#40]
`GetState()` has these match:
```
case libvirt.DOMAIN_SHUTDOWN:
    return state.Stopped, nil
case libvirt.DOMAIN_SHUTOFF:
    return state.Stopped, nil
```

`SHUTDOWN` means the VM is in the process of being shutdown, but it's still running, for example it's still visible in `virsh list` output.
On the other hand, `state.Stopped` assumes the VM is no longer running on the libvirt side.
If that `SHUTDOWN` state which should be short takes longer than expected, this can cause issues.
I've seen this in the CI for example with `crc stop` followed by `crc start`. `crc` thinks the VM is
stopped, but get an error from the machine driver when trying to start it.

**Comment by guillaumerose** [comment]
I observed it with this loop + crc stop:

```
$ repeat 1000  virsh --connect qemu:///system domstate crc --reason
running (booted)

running (booted)

running (booted)

in shutdown (unknown)

in shutdown (unknown)

shut off (shutdown)

shut off (shutdown)

shut off (shutdown)

shut off (shutdown)
```
